-- Create table for storing market data
create table public.market_data (
  id bigint generated by default as identity primary key,
  date date not null,
  ticker text not null,
  value numeric,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()),
  updated_at timestamp with time zone default timezone('utc'::text, now())
);

-- specific unique constraint for upsert
alter table public.market_data add constraint unique_ticker_date unique (ticker, date);

-- Enable Row Level Security (RLS)
alter table public.market_data enable row level security;

-- Create policy to allow all operations for authenticated users (service_role)
create policy "Allow all operations for service role"
on public.market_data
for all
to service_role
using (true)
with check (true);

-- Create policy to allow read access for anon (if needed)
create policy "Allow read access for anon"
on public.market_data
for select
to anon
using (true);
